### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by radarhere**

### CODE REVIEW

**Comment by hugovk** [comment]
I don't think it's important to say what the URL used to be, just change it to the new one.

**Comment by radarhere** [comment]
My thinking was to provide an explanation for why this repository is called 'python-pillow.github.io', when that's not where the site resides anymore.

That said, I've updated the file as you suggested.

**Comment by mudream4869** [comment]
or it should be https ?

**Comment by radarhere** [comment]
Okay, I've added a new commit to change it to https.

**Comment by radarhere** [comment]
The URL is no longer part of the README, so I'm closing this.

**Pull request closed without merging**
