### PR TITLE
Modernise docs links, fix invalid HTML

### PR DESCRIPTION
**Pull request by davidjb**
This updates the docs links so they always point to the 'latest' version on ReadTheDocs.  I also tidied a few bits of invalid HTML and http --> https in the process.

### CODE REVIEW

**Comment by hugovk** [comment]
Thank you!

I can't merge on this repo, but looks good.

Ping @aclark4life.

**Comment by wiredfool** [comment]
Latest is better than 3.0.x, but our setup these days is to have pillow.readthedocs.io redirect to the latest stable branch, not the latest unreleased docs.  Unfortunately, we can't do deep links that way.

**Comment by hugovk** [comment]
Let's stick a thing in the release checklist to update this.

**Comment by pjdelport** [comment]
This can probably be closed now that PR #10 is merged.

**Pull request closed without merging**
