### PR TITLE
Update website design

### PR DESCRIPTION
**Pull request by tfuxu**
This PR updates the look of the site and fixes some issues with responsiveness on mobile phones.

Updated look:
new-pillow-1

<details>
<summary>On mobile:</summary>

new-pillow-samsung-s20

</details>

PS. This was supposed to be a simple fix for oversized images on the webpage, but I ended up almost reformatting the whole site 😅️

### CODE REVIEW

**Comment by tfuxu** [comment]
@aclark4life I moved your job notice to the info bar below the navbar. Can it be here or would you want it to be placed somewhere else?
top-info

**Comment by aclark4life** [comment]
Well played, thank you!!

**Comment by tfuxu** [comment]
Thanks!
I checked the site, and it looks like I forgot to uncomment that info bar after testing 😬️. I'll make a quick PR to fix this

**Comment by tfuxu** [comment]
> Would you also like to have a look at https://pagespeed.web.dev/analysis/https-python-pillow-org/3h4xjteulj?form_factor=mobile and see if there's some accessibility and performance things that can be easily fixed?
> 
> (I've done some in #37)

Sure, I can try to fix some

**Pull request merged**
